language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23

before_install:
  - sudo apt-get install curl

script:
  ./gradlew build
  cd app\build\outputs\apk\app-debug.apk
  curl --upload-file app-debug.apk https://transfer.sh/app.apk
